// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: TELAS_PSU

#include "../ui.h"

lv_obj_t *ui_Tela_inicial = NULL;lv_obj_t *ui_barraStatus = NULL;lv_obj_t *ui_estadoRede = NULL;lv_obj_t *ui_estadoWiFi = NULL;lv_obj_t *ui_estadoServidor = NULL;lv_obj_t *ui_barBateria = NULL;lv_obj_t *ui_porcentagemBateria = NULL;lv_obj_t *ui_estadoNobreak = NULL;lv_obj_t *ui_botaoMonitor = NULL;lv_obj_t *ui_textoMonitor = NULL;
// event funtions
void ui_event_Tela_inicial( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Tela_dados, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Tela_dados_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_tela_lab, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_tela_lab_screen_init);
}
}

// build funtions

void ui_Tela_inicial_screen_init(void)
{
ui_Tela_inicial = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Tela_inicial, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_barraStatus = lv_obj_create(ui_Tela_inicial);
lv_obj_set_width( ui_barraStatus, 480);
lv_obj_set_height( ui_barraStatus, 30);
lv_obj_set_x( ui_barraStatus, 1 );
lv_obj_set_y( ui_barraStatus, -115 );
lv_obj_set_align( ui_barraStatus, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_barraStatus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_barraStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_barraStatus, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_barraStatus, lv_color_hex(0x30363D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_barraStatus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_barraStatus, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_barraStatus, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_estadoRede = lv_label_create(ui_barraStatus);
lv_obj_set_width( ui_estadoRede, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_estadoRede, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_estadoRede, -170 );
lv_obj_set_y( ui_estadoRede, -2 );
lv_obj_set_align( ui_estadoRede, LV_ALIGN_CENTER );
lv_label_set_text(ui_estadoRede,"FIBRA");
lv_obj_set_style_text_color(ui_estadoRede, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_estadoRede, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_estadoRede, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_estadoWiFi = lv_label_create(ui_barraStatus);
lv_obj_set_width( ui_estadoWiFi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_estadoWiFi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_estadoWiFi, 0 );
lv_obj_set_y( ui_estadoWiFi, -2 );
lv_obj_set_align( ui_estadoWiFi, LV_ALIGN_CENTER );
lv_label_set_text(ui_estadoWiFi,"");
lv_obj_set_style_text_color(ui_estadoWiFi, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_estadoWiFi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_estadoWiFi, &ui_font_Symbols, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_estadoServidor = lv_label_create(ui_barraStatus);
lv_obj_set_width( ui_estadoServidor, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_estadoServidor, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_estadoServidor, 170 );
lv_obj_set_y( ui_estadoServidor, -2 );
lv_obj_set_align( ui_estadoServidor, LV_ALIGN_CENTER );
lv_label_set_text(ui_estadoServidor,"");
lv_obj_set_style_text_color(ui_estadoServidor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_estadoServidor, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_estadoServidor, &ui_font_Symbols, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_barBateria = lv_bar_create(ui_Tela_inicial);
lv_bar_set_value(ui_barBateria,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_barBateria, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_barBateria, 320);
lv_obj_set_height( ui_barBateria, 12);
lv_obj_set_x( ui_barBateria, 3 );
lv_obj_set_y( ui_barBateria, 85 );
lv_obj_set_align( ui_barBateria, LV_ALIGN_TOP_MID );
lv_obj_set_style_radius(ui_barBateria, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_barBateria, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_barBateria, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_barBateria, lv_color_hex(0x30363D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_barBateria, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_barBateria, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_barBateria, 20, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_barBateria, lv_color_hex(0x00E5FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_barBateria, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_barBateria, lv_color_hex(0x00E5FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_barBateria, 150, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_barBateria, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_barBateria, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_porcentagemBateria = lv_label_create(ui_Tela_inicial);
lv_obj_set_width( ui_porcentagemBateria, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_porcentagemBateria, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_porcentagemBateria, 2 );
lv_obj_set_y( ui_porcentagemBateria, 48 );
lv_obj_set_align( ui_porcentagemBateria, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_porcentagemBateria,"100%");
lv_obj_set_style_text_color(ui_porcentagemBateria, lv_color_hex(0x00E5FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_porcentagemBateria, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_porcentagemBateria, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_estadoNobreak = lv_label_create(ui_Tela_inicial);
lv_obj_set_width( ui_estadoNobreak, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_estadoNobreak, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_estadoNobreak, -2 );
lv_obj_set_y( ui_estadoNobreak, 130 );
lv_obj_set_align( ui_estadoNobreak, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_estadoNobreak,"EM ESPERA");
lv_obj_set_style_text_color(ui_estadoNobreak, lv_color_hex(0x505050), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_estadoNobreak, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_estadoNobreak, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_botaoMonitor = lv_btn_create(ui_Tela_inicial);
lv_obj_set_width( ui_botaoMonitor, 120);
lv_obj_set_height( ui_botaoMonitor, 50);
lv_obj_set_x( ui_botaoMonitor, -20 );
lv_obj_set_y( ui_botaoMonitor, -20 );
lv_obj_set_align( ui_botaoMonitor, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_botaoMonitor, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_botaoMonitor, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_botaoMonitor, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_botaoMonitor, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_botaoMonitor, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_botaoMonitor, lv_color_hex(0x00E5FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_botaoMonitor, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_botaoMonitor, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_textoMonitor = lv_label_create(ui_botaoMonitor);
lv_obj_set_width( ui_textoMonitor, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_textoMonitor, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_textoMonitor, -1 );
lv_obj_set_y( ui_textoMonitor, 9 );
lv_obj_set_align( ui_textoMonitor, LV_ALIGN_CENTER );
lv_label_set_text(ui_textoMonitor,"MONITOR\n");
lv_obj_set_style_text_color(ui_textoMonitor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_textoMonitor, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_textoMonitor, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Tela_inicial, ui_event_Tela_inicial, LV_EVENT_ALL, NULL);

}

void ui_Tela_inicial_screen_destroy(void)
{
   if (ui_Tela_inicial) lv_obj_del(ui_Tela_inicial);

// NULL screen variables
ui_Tela_inicial= NULL;
ui_barraStatus= NULL;
ui_estadoRede= NULL;
ui_estadoWiFi= NULL;
ui_estadoServidor= NULL;
ui_barBateria= NULL;
ui_porcentagemBateria= NULL;
ui_estadoNobreak= NULL;
ui_botaoMonitor= NULL;
ui_textoMonitor= NULL;

}
