// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: TELAS_PSU

#include "../ui.h"

lv_obj_t *ui_Tela_rede = NULL;lv_obj_t *ui_barraStatus3 = NULL;lv_obj_t *ui_estadoRede3 = NULL;lv_obj_t *ui_estadoWiFi3 = NULL;lv_obj_t *ui_estadoServidor3 = NULL;lv_obj_t *ui_barraVertical2 = NULL;lv_obj_t *ui_barraHorizontal1 = NULL;lv_obj_t *ui_tensaoBatr = NULL;lv_obj_t *ui_dados5G = NULL;lv_obj_t *ui_injetada = NULL;lv_obj_t *ui_consumida = NULL;lv_obj_t *ui_dadosFibra = NULL;lv_obj_t *ui_valor5G = NULL;lv_obj_t *ui_valorInjetada = NULL;lv_obj_t *ui_valorConsumida = NULL;
// event funtions
void ui_event_Tela_rede( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Tela_dados, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Tela_dados_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_tela_lab, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_tela_lab_screen_init);
}
}

// build funtions

void ui_Tela_rede_screen_init(void)
{
ui_Tela_rede = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Tela_rede, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_barraStatus3 = lv_obj_create(ui_Tela_rede);
lv_obj_set_width( ui_barraStatus3, 480);
lv_obj_set_height( ui_barraStatus3, 30);
lv_obj_set_x( ui_barraStatus3, 1 );
lv_obj_set_y( ui_barraStatus3, -115 );
lv_obj_set_align( ui_barraStatus3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_barraStatus3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_barraStatus3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_barraStatus3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_barraStatus3, lv_color_hex(0x30363D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_barraStatus3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_barraStatus3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_barraStatus3, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_estadoRede3 = lv_label_create(ui_barraStatus3);
lv_obj_set_width( ui_estadoRede3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_estadoRede3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_estadoRede3, -170 );
lv_obj_set_y( ui_estadoRede3, -2 );
lv_obj_set_align( ui_estadoRede3, LV_ALIGN_CENTER );
lv_label_set_text(ui_estadoRede3,"FIBRA");
lv_obj_set_style_text_color(ui_estadoRede3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_estadoRede3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_estadoRede3, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_estadoWiFi3 = lv_label_create(ui_barraStatus3);
lv_obj_set_width( ui_estadoWiFi3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_estadoWiFi3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_estadoWiFi3, 0 );
lv_obj_set_y( ui_estadoWiFi3, -2 );
lv_obj_set_align( ui_estadoWiFi3, LV_ALIGN_CENTER );
lv_label_set_text(ui_estadoWiFi3,"");
lv_obj_set_style_text_color(ui_estadoWiFi3, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_estadoWiFi3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_estadoWiFi3, &ui_font_Symbols, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_estadoServidor3 = lv_label_create(ui_barraStatus3);
lv_obj_set_width( ui_estadoServidor3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_estadoServidor3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_estadoServidor3, 170 );
lv_obj_set_y( ui_estadoServidor3, -2 );
lv_obj_set_align( ui_estadoServidor3, LV_ALIGN_CENTER );
lv_label_set_text(ui_estadoServidor3,"");
lv_obj_set_style_text_color(ui_estadoServidor3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_estadoServidor3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_estadoServidor3, &ui_font_Symbols, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_barraVertical2 = lv_obj_create(ui_Tela_rede);
lv_obj_set_width( ui_barraVertical2, 1);
lv_obj_set_height( ui_barraVertical2, 235);
lv_obj_set_x( ui_barraVertical2, 0 );
lv_obj_set_y( ui_barraVertical2, 15 );
lv_obj_set_align( ui_barraVertical2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_barraVertical2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_barraVertical2, lv_color_hex(0x30363D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_barraVertical2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_barraHorizontal1 = lv_obj_create(ui_Tela_rede);
lv_obj_set_width( ui_barraHorizontal1, 480);
lv_obj_set_height( ui_barraHorizontal1, 1);
lv_obj_set_x( ui_barraHorizontal1, 0 );
lv_obj_set_y( ui_barraHorizontal1, 146 );
lv_obj_set_align( ui_barraHorizontal1, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_barraHorizontal1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_barraHorizontal1, lv_color_hex(0x30363D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_barraHorizontal1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tensaoBatr = lv_label_create(ui_Tela_rede);
lv_obj_set_width( ui_tensaoBatr, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tensaoBatr, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tensaoBatr, -120 );
lv_obj_set_y( ui_tensaoBatr, -60 );
lv_obj_set_align( ui_tensaoBatr, LV_ALIGN_CENTER );
lv_label_set_text(ui_tensaoBatr,"FIBRA:");
lv_obj_set_style_text_color(ui_tensaoBatr, lv_color_hex(0x505050), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tensaoBatr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dados5G = lv_label_create(ui_Tela_rede);
lv_obj_set_width( ui_dados5G, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dados5G, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dados5G, 120 );
lv_obj_set_y( ui_dados5G, -60 );
lv_obj_set_align( ui_dados5G, LV_ALIGN_CENTER );
lv_label_set_text(ui_dados5G,"5G:");
lv_obj_set_style_text_color(ui_dados5G, lv_color_hex(0x505050), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_dados5G, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_injetada = lv_label_create(ui_Tela_rede);
lv_obj_set_width( ui_injetada, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_injetada, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_injetada, -120 );
lv_obj_set_y( ui_injetada, 60 );
lv_obj_set_align( ui_injetada, LV_ALIGN_CENTER );
lv_label_set_text(ui_injetada,"INJETADA:");
lv_obj_set_style_text_color(ui_injetada, lv_color_hex(0x505050), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_injetada, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_consumida = lv_label_create(ui_Tela_rede);
lv_obj_set_width( ui_consumida, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_consumida, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_consumida, 120 );
lv_obj_set_y( ui_consumida, 60 );
lv_obj_set_align( ui_consumida, LV_ALIGN_CENTER );
lv_label_set_text(ui_consumida,"CONSUMIDA:");
lv_obj_set_style_text_color(ui_consumida, lv_color_hex(0x505050), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_consumida, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dadosFibra = lv_label_create(ui_Tela_rede);
lv_obj_set_width( ui_dadosFibra, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dadosFibra, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dadosFibra, -120 );
lv_obj_set_y( ui_dadosFibra, -30 );
lv_obj_set_align( ui_dadosFibra, LV_ALIGN_CENTER );
lv_label_set_text(ui_dadosFibra,"-- GB");
lv_obj_set_style_text_color(ui_dadosFibra, lv_color_hex(0x00E5FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_dadosFibra, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dadosFibra, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_valor5G = lv_label_create(ui_Tela_rede);
lv_obj_set_width( ui_valor5G, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_valor5G, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_valor5G, 120 );
lv_obj_set_y( ui_valor5G, -30 );
lv_obj_set_align( ui_valor5G, LV_ALIGN_CENTER );
lv_label_set_text(ui_valor5G,"-- MB");
lv_obj_set_style_text_color(ui_valor5G, lv_color_hex(0x00E5FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_valor5G, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_valor5G, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_valorInjetada = lv_label_create(ui_Tela_rede);
lv_obj_set_width( ui_valorInjetada, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_valorInjetada, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_valorInjetada, -120 );
lv_obj_set_y( ui_valorInjetada, 90 );
lv_obj_set_align( ui_valorInjetada, LV_ALIGN_CENTER );
lv_label_set_text(ui_valorInjetada,"-- kWh");
lv_obj_set_style_text_font(ui_valorInjetada, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_valorConsumida = lv_label_create(ui_Tela_rede);
lv_obj_set_width( ui_valorConsumida, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_valorConsumida, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_valorConsumida, 120 );
lv_obj_set_y( ui_valorConsumida, 90 );
lv_obj_set_align( ui_valorConsumida, LV_ALIGN_CENTER );
lv_label_set_text(ui_valorConsumida,"-- kWh");
lv_obj_set_style_text_font(ui_valorConsumida, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Tela_rede, ui_event_Tela_rede, LV_EVENT_ALL, NULL);

}

void ui_Tela_rede_screen_destroy(void)
{
   if (ui_Tela_rede) lv_obj_del(ui_Tela_rede);

// NULL screen variables
ui_Tela_rede= NULL;
ui_barraStatus3= NULL;
ui_estadoRede3= NULL;
ui_estadoWiFi3= NULL;
ui_estadoServidor3= NULL;
ui_barraVertical2= NULL;
ui_barraHorizontal1= NULL;
ui_tensaoBatr= NULL;
ui_dados5G= NULL;
ui_injetada= NULL;
ui_consumida= NULL;
ui_dadosFibra= NULL;
ui_valor5G= NULL;
ui_valorInjetada= NULL;
ui_valorConsumida= NULL;

}
