// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: TELAS_PSU

#ifndef UI_TELA_REDE_H
#define UI_TELA_REDE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Tela_rede
extern void ui_Tela_rede_screen_init(void);
extern void ui_Tela_rede_screen_destroy(void);
extern void ui_event_Tela_rede( lv_event_t * e);
extern lv_obj_t *ui_Tela_rede;
extern lv_obj_t *ui_barraStatus3;
extern lv_obj_t *ui_estadoRede3;
extern lv_obj_t *ui_estadoWiFi3;
extern lv_obj_t *ui_estadoServidor3;
extern lv_obj_t *ui_barraVertical2;
extern lv_obj_t *ui_barraHorizontal1;
extern lv_obj_t *ui_tensaoBatr;
extern lv_obj_t *ui_dados5G;
extern lv_obj_t *ui_injetada;
extern lv_obj_t *ui_consumida;
extern lv_obj_t *ui_dadosFibra;
extern lv_obj_t *ui_valor5G;
extern lv_obj_t *ui_valorInjetada;
extern lv_obj_t *ui_valorConsumida;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

