// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: TELAS_PSU

#include "../ui.h"

lv_obj_t *ui_Tela_dados = NULL;lv_obj_t *ui_barraStatus2 = NULL;lv_obj_t *ui_estadoRede2 = NULL;lv_obj_t *ui_estadoWiFi2 = NULL;lv_obj_t *ui_estadoServidor2 = NULL;lv_obj_t *ui_barraVertical = NULL;lv_obj_t *ui_barraHorizontal = NULL;lv_obj_t *ui_bateria = NULL;lv_obj_t *ui_porcentagemBateria1 = NULL;lv_obj_t *ui_tempUmidade = NULL;lv_obj_t *ui_cooler = NULL;lv_obj_t *ui_tensaoDC = NULL;lv_obj_t *ui_tensaoAC = NULL;lv_obj_t *ui_valoresTempH = NULL;lv_obj_t *ui_potenciaCooler = NULL;
// event funtions
void ui_event_Tela_dados( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Tela_inicial, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Tela_inicial_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Tela_rede, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Tela_rede_screen_init);
}
}

// build funtions

void ui_Tela_dados_screen_init(void)
{
ui_Tela_dados = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Tela_dados, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_barraStatus2 = lv_obj_create(ui_Tela_dados);
lv_obj_set_width( ui_barraStatus2, 480);
lv_obj_set_height( ui_barraStatus2, 30);
lv_obj_set_x( ui_barraStatus2, 1 );
lv_obj_set_y( ui_barraStatus2, -115 );
lv_obj_set_align( ui_barraStatus2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_barraStatus2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_barraStatus2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_barraStatus2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_barraStatus2, lv_color_hex(0x30363D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_barraStatus2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_barraStatus2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_barraStatus2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_estadoRede2 = lv_label_create(ui_barraStatus2);
lv_obj_set_width( ui_estadoRede2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_estadoRede2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_estadoRede2, -170 );
lv_obj_set_y( ui_estadoRede2, -2 );
lv_obj_set_align( ui_estadoRede2, LV_ALIGN_CENTER );
lv_label_set_text(ui_estadoRede2,"FIBRA");
lv_obj_set_style_text_color(ui_estadoRede2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_estadoRede2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_estadoRede2, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_estadoWiFi2 = lv_label_create(ui_barraStatus2);
lv_obj_set_width( ui_estadoWiFi2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_estadoWiFi2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_estadoWiFi2, 0 );
lv_obj_set_y( ui_estadoWiFi2, -2 );
lv_obj_set_align( ui_estadoWiFi2, LV_ALIGN_CENTER );
lv_label_set_text(ui_estadoWiFi2,"");
lv_obj_set_style_text_color(ui_estadoWiFi2, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_estadoWiFi2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_estadoWiFi2, &ui_font_Symbols, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_estadoServidor2 = lv_label_create(ui_barraStatus2);
lv_obj_set_width( ui_estadoServidor2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_estadoServidor2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_estadoServidor2, 170 );
lv_obj_set_y( ui_estadoServidor2, -2 );
lv_obj_set_align( ui_estadoServidor2, LV_ALIGN_CENTER );
lv_label_set_text(ui_estadoServidor2,"");
lv_obj_set_style_text_color(ui_estadoServidor2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_estadoServidor2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_estadoServidor2, &ui_font_Symbols, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_barraVertical = lv_obj_create(ui_Tela_dados);
lv_obj_set_width( ui_barraVertical, 1);
lv_obj_set_height( ui_barraVertical, 240);
lv_obj_set_x( ui_barraVertical, 0 );
lv_obj_set_y( ui_barraVertical, 18 );
lv_obj_set_align( ui_barraVertical, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_barraVertical, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_barraVertical, lv_color_hex(0x30363D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_barraVertical, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_barraHorizontal = lv_obj_create(ui_Tela_dados);
lv_obj_set_width( ui_barraHorizontal, 480);
lv_obj_set_height( ui_barraHorizontal, 1);
lv_obj_set_x( ui_barraHorizontal, 0 );
lv_obj_set_y( ui_barraHorizontal, 146 );
lv_obj_set_align( ui_barraHorizontal, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_barraHorizontal, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_barraHorizontal, lv_color_hex(0x30363D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_barraHorizontal, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bateria = lv_label_create(ui_Tela_dados);
lv_obj_set_width( ui_bateria, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bateria, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bateria, -120 );
lv_obj_set_y( ui_bateria, -60 );
lv_obj_set_align( ui_bateria, LV_ALIGN_CENTER );
lv_label_set_text(ui_bateria,"Bateria:");
lv_obj_set_style_text_color(ui_bateria, lv_color_hex(0x505050), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_bateria, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_porcentagemBateria1 = lv_label_create(ui_Tela_dados);
lv_obj_set_width( ui_porcentagemBateria1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_porcentagemBateria1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_porcentagemBateria1, 120 );
lv_obj_set_y( ui_porcentagemBateria1, -60 );
lv_obj_set_align( ui_porcentagemBateria1, LV_ALIGN_CENTER );
lv_label_set_text(ui_porcentagemBateria1,"Rede AC:");
lv_obj_set_style_text_color(ui_porcentagemBateria1, lv_color_hex(0x505050), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_porcentagemBateria1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tempUmidade = lv_label_create(ui_Tela_dados);
lv_obj_set_width( ui_tempUmidade, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tempUmidade, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tempUmidade, -120 );
lv_obj_set_y( ui_tempUmidade, 60 );
lv_obj_set_align( ui_tempUmidade, LV_ALIGN_CENTER );
lv_label_set_text(ui_tempUmidade,"Temp/Umidade:");
lv_obj_set_style_text_color(ui_tempUmidade, lv_color_hex(0x505050), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tempUmidade, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cooler = lv_label_create(ui_Tela_dados);
lv_obj_set_width( ui_cooler, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_cooler, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_cooler, 120 );
lv_obj_set_y( ui_cooler, 60 );
lv_obj_set_align( ui_cooler, LV_ALIGN_CENTER );
lv_label_set_text(ui_cooler,"Cooler:");
lv_obj_set_style_text_color(ui_cooler, lv_color_hex(0x505050), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_cooler, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tensaoDC = lv_label_create(ui_Tela_dados);
lv_obj_set_width( ui_tensaoDC, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tensaoDC, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tensaoDC, -120 );
lv_obj_set_y( ui_tensaoDC, -30 );
lv_obj_set_align( ui_tensaoDC, LV_ALIGN_CENTER );
lv_label_set_text(ui_tensaoDC,"41.5 V");
lv_obj_set_style_text_color(ui_tensaoDC, lv_color_hex(0x00E5FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tensaoDC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tensaoDC, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tensaoAC = lv_label_create(ui_Tela_dados);
lv_obj_set_width( ui_tensaoAC, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tensaoAC, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tensaoAC, 120 );
lv_obj_set_y( ui_tensaoAC, -30 );
lv_obj_set_align( ui_tensaoAC, LV_ALIGN_CENTER );
lv_label_set_text(ui_tensaoAC,"220 V");
lv_obj_set_style_text_color(ui_tensaoAC, lv_color_hex(0x00E5FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tensaoAC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tensaoAC, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_valoresTempH = lv_label_create(ui_Tela_dados);
lv_obj_set_width( ui_valoresTempH, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_valoresTempH, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_valoresTempH, -120 );
lv_obj_set_y( ui_valoresTempH, 90 );
lv_obj_set_align( ui_valoresTempH, LV_ALIGN_CENTER );
lv_label_set_text(ui_valoresTempH,"34°C / 45%");
lv_obj_set_style_text_font(ui_valoresTempH, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_potenciaCooler = lv_label_create(ui_Tela_dados);
lv_obj_set_width( ui_potenciaCooler, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_potenciaCooler, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_potenciaCooler, 120 );
lv_obj_set_y( ui_potenciaCooler, 90 );
lv_obj_set_align( ui_potenciaCooler, LV_ALIGN_CENTER );
lv_label_set_text(ui_potenciaCooler,"50%");
lv_obj_set_style_text_font(ui_potenciaCooler, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Tela_dados, ui_event_Tela_dados, LV_EVENT_ALL, NULL);

}

void ui_Tela_dados_screen_destroy(void)
{
   if (ui_Tela_dados) lv_obj_del(ui_Tela_dados);

// NULL screen variables
ui_Tela_dados= NULL;
ui_barraStatus2= NULL;
ui_estadoRede2= NULL;
ui_estadoWiFi2= NULL;
ui_estadoServidor2= NULL;
ui_barraVertical= NULL;
ui_barraHorizontal= NULL;
ui_bateria= NULL;
ui_porcentagemBateria1= NULL;
ui_tempUmidade= NULL;
ui_cooler= NULL;
ui_tensaoDC= NULL;
ui_tensaoAC= NULL;
ui_valoresTempH= NULL;
ui_potenciaCooler= NULL;

}
