// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: TELAS_PSU

#ifndef UI_TELA_INICIAL_H
#define UI_TELA_INICIAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Tela_inicial
extern void ui_Tela_inicial_screen_init(void);
extern void ui_Tela_inicial_screen_destroy(void);
extern void ui_event_Tela_inicial( lv_event_t * e);
extern lv_obj_t *ui_Tela_inicial;
extern lv_obj_t *ui_barraStatus;
extern lv_obj_t *ui_estadoRede;
extern lv_obj_t *ui_estadoWiFi;
extern lv_obj_t *ui_estadoServidor;
extern lv_obj_t *ui_barBateria;
extern lv_obj_t *ui_porcentagemBateria;
extern lv_obj_t *ui_estadoNobreak;
extern lv_obj_t *ui_botaoMonitor;
extern lv_obj_t *ui_textoMonitor;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

