// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: TELAS_PSU

#include "../ui.h"

lv_obj_t *ui_tela_shutdown = NULL;lv_obj_t *ui_painelShutdown = NULL;lv_obj_t *ui_temporizador = NULL;lv_obj_t *ui_sistemaCritico = NULL;lv_obj_t *ui_desligandoSeg = NULL;
// event funtions

// build funtions

void ui_tela_shutdown_screen_init(void)
{
ui_tela_shutdown = lv_obj_create(NULL);
lv_obj_clear_flag( ui_tela_shutdown, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_tela_shutdown, lv_color_hex(0x400000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_tela_shutdown, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_painelShutdown = lv_obj_create(ui_tela_shutdown);
lv_obj_set_width( ui_painelShutdown, 220);
lv_obj_set_height( ui_painelShutdown, 150);
lv_obj_set_align( ui_painelShutdown, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_painelShutdown, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_painelShutdown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_painelShutdown, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_painelShutdown, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_painelShutdown, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_painelShutdown, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_painelShutdown, lv_color_hex(0xFF3D00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_painelShutdown, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temporizador = lv_label_create(ui_painelShutdown);
lv_obj_set_width( ui_temporizador, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temporizador, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_temporizador, LV_ALIGN_CENTER );
lv_label_set_text(ui_temporizador,"30");
lv_obj_set_style_text_color(ui_temporizador, lv_color_hex(0xFF3D00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_temporizador, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_temporizador, &ui_font_Shutdown, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sistemaCritico = lv_label_create(ui_tela_shutdown);
lv_obj_set_width( ui_sistemaCritico, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_sistemaCritico, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_sistemaCritico, 0 );
lv_obj_set_y( ui_sistemaCritico, -110 );
lv_obj_set_align( ui_sistemaCritico, LV_ALIGN_CENTER );
lv_label_set_text(ui_sistemaCritico,"SISTEMA CRITICO");

ui_desligandoSeg = lv_label_create(ui_tela_shutdown);
lv_obj_set_width( ui_desligandoSeg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_desligandoSeg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_desligandoSeg, 0 );
lv_obj_set_y( ui_desligandoSeg, 105 );
lv_obj_set_align( ui_desligandoSeg, LV_ALIGN_CENTER );
lv_label_set_text(ui_desligandoSeg,"DESLIGANDO EM SEGUNDOS");

}

void ui_tela_shutdown_screen_destroy(void)
{
   if (ui_tela_shutdown) lv_obj_del(ui_tela_shutdown);

// NULL screen variables
ui_tela_shutdown= NULL;
ui_painelShutdown= NULL;
ui_temporizador= NULL;
ui_sistemaCritico= NULL;
ui_desligandoSeg= NULL;

}
