// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: TELAS_PSU

#ifndef UI_TELA_SHUTDOWN_H
#define UI_TELA_SHUTDOWN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_tela_shutdown
extern void ui_tela_shutdown_screen_init(void);
extern void ui_tela_shutdown_screen_destroy(void);
extern lv_obj_t *ui_tela_shutdown;
extern lv_obj_t *ui_painelShutdown;
extern lv_obj_t *ui_temporizador;
extern lv_obj_t *ui_sistemaCritico;
extern lv_obj_t *ui_desligandoSeg;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

