// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: TELAS_PSU

#ifndef UI_TELA_LAB_H
#define UI_TELA_LAB_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_tela_lab
extern void ui_tela_lab_screen_init(void);
extern void ui_tela_lab_screen_destroy(void);
extern void ui_event_tela_lab( lv_event_t * e);
extern lv_obj_t *ui_tela_lab;
extern lv_obj_t *ui_barraStatus4;
extern lv_obj_t *ui_estadoRede4;
extern lv_obj_t *ui_estadoWiFi4;
extern lv_obj_t *ui_estadoServidor4;
extern lv_obj_t *ui_botaoBench;
extern lv_obj_t *ui_textoBench;
extern lv_obj_t *ui_benchAnterior;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

