// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: TELAS_PSU

#include "../ui.h"

lv_obj_t *ui_tela_lab = NULL;lv_obj_t *ui_barraStatus4 = NULL;lv_obj_t *ui_estadoRede4 = NULL;lv_obj_t *ui_estadoWiFi4 = NULL;lv_obj_t *ui_estadoServidor4 = NULL;lv_obj_t *ui_botaoBench = NULL;lv_obj_t *ui_textoBench = NULL;lv_obj_t *ui_benchAnterior = NULL;
// event funtions
void ui_event_tela_lab( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Tela_rede, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Tela_rede_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Tela_inicial, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Tela_inicial_screen_init);
}
}

// build funtions

void ui_tela_lab_screen_init(void)
{
ui_tela_lab = lv_obj_create(NULL);
lv_obj_clear_flag( ui_tela_lab, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_barraStatus4 = lv_obj_create(ui_tela_lab);
lv_obj_set_width( ui_barraStatus4, 480);
lv_obj_set_height( ui_barraStatus4, 30);
lv_obj_set_x( ui_barraStatus4, 1 );
lv_obj_set_y( ui_barraStatus4, -115 );
lv_obj_set_align( ui_barraStatus4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_barraStatus4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_barraStatus4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_barraStatus4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_barraStatus4, lv_color_hex(0x30363D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_barraStatus4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_barraStatus4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_barraStatus4, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_estadoRede4 = lv_label_create(ui_barraStatus4);
lv_obj_set_width( ui_estadoRede4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_estadoRede4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_estadoRede4, -170 );
lv_obj_set_y( ui_estadoRede4, -2 );
lv_obj_set_align( ui_estadoRede4, LV_ALIGN_CENTER );
lv_label_set_text(ui_estadoRede4,"FIBRA");
lv_obj_set_style_text_color(ui_estadoRede4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_estadoRede4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_estadoRede4, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_estadoWiFi4 = lv_label_create(ui_barraStatus4);
lv_obj_set_width( ui_estadoWiFi4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_estadoWiFi4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_estadoWiFi4, 0 );
lv_obj_set_y( ui_estadoWiFi4, -2 );
lv_obj_set_align( ui_estadoWiFi4, LV_ALIGN_CENTER );
lv_label_set_text(ui_estadoWiFi4,"");
lv_obj_set_style_text_color(ui_estadoWiFi4, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_estadoWiFi4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_estadoWiFi4, &ui_font_Symbols, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_estadoServidor4 = lv_label_create(ui_barraStatus4);
lv_obj_set_width( ui_estadoServidor4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_estadoServidor4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_estadoServidor4, 170 );
lv_obj_set_y( ui_estadoServidor4, -2 );
lv_obj_set_align( ui_estadoServidor4, LV_ALIGN_CENTER );
lv_label_set_text(ui_estadoServidor4,"");
lv_obj_set_style_text_color(ui_estadoServidor4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_estadoServidor4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_estadoServidor4, &ui_font_Symbols, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_botaoBench = lv_btn_create(ui_tela_lab);
lv_obj_set_width( ui_botaoBench, 180);
lv_obj_set_height( ui_botaoBench, 80);
lv_obj_set_x( ui_botaoBench, 0 );
lv_obj_set_y( ui_botaoBench, -39 );
lv_obj_set_align( ui_botaoBench, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_botaoBench, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_botaoBench, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_botaoBench, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_botaoBench, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_botaoBench, lv_color_hex(0x00E5FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_botaoBench, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_botaoBench, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_textoBench = lv_label_create(ui_botaoBench);
lv_obj_set_width( ui_textoBench, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_textoBench, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_textoBench, LV_ALIGN_CENTER );
lv_label_set_text(ui_textoBench,"BENCHMARK");

ui_benchAnterior = lv_label_create(ui_tela_lab);
lv_obj_set_width( ui_benchAnterior, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_benchAnterior, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_benchAnterior, 0 );
lv_obj_set_y( ui_benchAnterior, 50 );
lv_obj_set_align( ui_benchAnterior, LV_ALIGN_CENTER );
lv_label_set_text(ui_benchAnterior,"ANTERIOR: 382Wh / 5h10m");

lv_obj_add_event_cb(ui_tela_lab, ui_event_tela_lab, LV_EVENT_ALL, NULL);

}

void ui_tela_lab_screen_destroy(void)
{
   if (ui_tela_lab) lv_obj_del(ui_tela_lab);

// NULL screen variables
ui_tela_lab= NULL;
ui_barraStatus4= NULL;
ui_estadoRede4= NULL;
ui_estadoWiFi4= NULL;
ui_estadoServidor4= NULL;
ui_botaoBench= NULL;
ui_textoBench= NULL;
ui_benchAnterior= NULL;

}
