// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: TELAS_PSU

#ifndef UI_TELA_DADOS_H
#define UI_TELA_DADOS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Tela_dados
extern void ui_Tela_dados_screen_init(void);
extern void ui_Tela_dados_screen_destroy(void);
extern void ui_event_Tela_dados( lv_event_t * e);
extern lv_obj_t *ui_Tela_dados;
extern lv_obj_t *ui_barraStatus2;
extern lv_obj_t *ui_estadoRede2;
extern lv_obj_t *ui_estadoWiFi2;
extern lv_obj_t *ui_estadoServidor2;
extern lv_obj_t *ui_barraVertical;
extern lv_obj_t *ui_barraHorizontal;
extern lv_obj_t *ui_bateria;
extern lv_obj_t *ui_porcentagemBateria1;
extern lv_obj_t *ui_tempUmidade;
extern lv_obj_t *ui_cooler;
extern lv_obj_t *ui_tensaoDC;
extern lv_obj_t *ui_tensaoAC;
extern lv_obj_t *ui_valoresTempH;
extern lv_obj_t *ui_potenciaCooler;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

