// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: TELAS_PSU

#ifndef _TELAS_PSU_UI_H
#define _TELAS_PSU_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Tela_inicial.h"
#include "screens/ui_Tela_dados.h"
#include "screens/ui_Tela_rede.h"
#include "screens/ui_tela_lab.h"
#include "screens/ui_tela_shutdown.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// FONTS
LV_FONT_DECLARE( ui_font_Shutdown);
LV_FONT_DECLARE( ui_font_Symbols);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
